### ISSUE TITLE
autocomplete？

### ISSUE THREAD

**Issue by justmd5** [rgcr/m-cli#23] opened 2016-07-15 09:57 UTC
### autocomplete？please。tks

**Comment by radiovisual** [comment] 2016-07-15 16:27
This issue is a duplicate of #14 and #29

**Comment by rgcr** [comment] 2016-07-17 02:21
Thanks to @yazgazan #33 we have completions for bash and zsh now.

**Closed by rgcr** 2016-07-17 02:21 UTC
Labels: duplicate, enhancement

**Comment by devxoul** [comment] 2016-08-07 21:04
If your autocompletion does not work: [this link](http://apple.stackexchange.com/a/195477/196344) helped me.
